 type Difficulty = 'easy' | 'medium' | 'hard';
type Category = 'array' | 'string' | 'object' | 'function' | 'logic';

export type Challenge = {
  id: number;
  title: string;
  difficulty: Difficulty;
  category: Category;
  description: string;
  starterCode: string;
};

 
 
export const challenges: Challenge[] = [
  {
    id: 1,
    title: 'معکوس کردن آرایه — reverseArray()',
    difficulty: 'easy',
    category: 'array',
    description: 'یه آرایه بگیر و معکوسش کن بدون استفاده از reverse()',
    starterCode: 'function reverseArray(arr) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 2,
    title: 'پیدا کردن بزرگترین عدد — findMax()',
    difficulty: 'easy',
    category: 'array',
    description: 'بزرگترین عدد رو از یه آرایه پیدا کن',
    starterCode: 'function findMax(arr) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 3,
    title: 'معکوس کردن رشته — reverseString()',
    difficulty: 'easy',
    category: 'string',
    description: 'یه رشته بگیر و کاراکترهاش رو معکوس کن',
    starterCode: 'function reverseString(str) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 4,
    title: 'حذف تکراری‌ها — removeDuplicates()',
    difficulty: 'easy',
    category: 'array',
    description: 'المان‌های تکراری رو از یه آرایه حذف کن',
    starterCode: 'function removeDuplicates(arr) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 5,
    title: 'جمع اعداد آرایه — sumArray()',
    difficulty: 'easy',
    category: 'array',
    description: 'مجموع تمام اعداد یه آرایه رو برگردون',
    starterCode: 'function sumArray(arr) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 6,
    title: 'بررسی پالیندروم — isPalindrome()',
    difficulty: 'easy',
    category: 'string',
    description: 'چک کن آیا یه رشته پالیندروم هست یا نه (مثل racecar)',
    starterCode: 'function isPalindrome(str) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 7,
    title: 'شمارش حروف — countChars()',
    difficulty: 'easy',
    category: 'string',
    description: 'تعداد هر حرف رو در یه رشته بشمار و به صورت آبجکت برگردون',
    starterCode: 'function countChars(str) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 8,
    title: 'فیلتر اعداد زوج — filterEven()',
    difficulty: 'easy',
    category: 'array',
    description: 'فقط اعداد زوج رو از یه آرایه برگردون',
    starterCode: 'function filterEven(arr) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 9,
    title: 'بزرگ کردن اول کلمه — capitalizeWords()',
    difficulty: 'easy',
    category: 'string',
    description: 'حرف اول هر کلمه رو بزرگ کن',
    starterCode: 'function capitalizeWords(str) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 10,
    title: 'پیدا کردن کوچکترین عدد — findMin()',
    difficulty: 'easy',
    category: 'array',
    description: 'کوچکترین عدد رو از یه آرایه پیدا کن',
    starterCode: 'function findMin(arr) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 11,
    title: 'مرتب‌سازی صعودی — sortAscending()',
    difficulty: 'easy',
    category: 'array',
    description: 'آرایه‌ای از اعداد رو به صورت صعودی مرتب کن',
    starterCode: 'function sortAscending(arr) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 12,
    title: 'بررسی عدد اول — isPrime()',
    difficulty: 'medium',
    category: 'logic',
    description: 'چک کن آیا یه عدد، عدد اول هست یا نه',
    starterCode: 'function isPrime(num) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 13,
    title: 'دنباله فیبوناچی — fibonacci()',
    difficulty: 'medium',
    category: 'logic',
    description: 'n امین عدد دنباله فیبوناچی رو برگردون',
    starterCode: 'function fibonacci(n) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 14,
    title: 'تخت کردن آرایه — flattenArray()',
    difficulty: 'medium',
    category: 'array',
    description: 'یه آرایه تو در تو رو به یه آرایه یک‌بعدی تبدیل کن',
    starterCode: 'function flattenArray(arr) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 15,
    title: 'گروه‌بندی بر اساس ویژگی — groupBy()',
    difficulty: 'medium',
    category: 'object',
    description: 'آرایه‌ای از آبجکت‌ها رو بر اساس یه ویژگی گروه‌بندی کن',
    starterCode: 'function groupBy(arr, key) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 16,
    title: 'ادغام دو آرایه مرتب — mergeSorted()',
    difficulty: 'medium',
    category: 'array',
    description: 'دو آرایه مرتب‌شده رو ادغام کن و نتیجه رو مرتب برگردون',
    starterCode: 'function mergeSorted(arr1, arr2) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 17,
    title: 'تقاطع آرایه‌ها — intersection()',
    difficulty: 'medium',
    category: 'array',
    description: 'المان‌های مشترک دو آرایه رو پیدا کن',
    starterCode: 'function intersection(arr1, arr2) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 18,
    title: 'تأخیر در اجرا — debounce()',
    difficulty: 'hard',
    category: 'function',
    description: 'یه تابع debounce بنویس که اجرای تابع رو به تأخیر بندازه',
    starterCode: 'function debounce(fn, delay) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 19,
    title: 'کپی عمیق — deepClone()',
    difficulty: 'hard',
    category: 'object',
    description: 'یه کپی عمیق از یه آبجکت تو در تو بساز',
    starterCode: 'function deepClone(obj) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 20,
    title: 'Curry کردن تابع — curry()',
    difficulty: 'hard',
    category: 'function',
    description: 'یه تابع با چند آرگومان رو به تابع curry تبدیل کن',
    starterCode: 'function curry(fn) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 21,
    title: 'میانگین آرایه — average()',
    difficulty: 'easy',
    category: 'array',
    description: 'میانگین اعداد یه آرایه رو حساب کن',
    starterCode: 'function average(arr) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 22,
    title: 'بررسی آنگرام — isAnagram()',
    difficulty: 'medium',
    category: 'string',
    description: 'چک کن آیا دو رشته آنگرام هم هستن یا نه',
    starterCode: 'function isAnagram(str1, str2) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 23,
    title: 'چرخاندن آرایه — rotateArray()',
    difficulty: 'medium',
    category: 'array',
    description: 'آرایه رو k مرحله به چپ یا راست بچرخون',
    starterCode: 'function rotateArray(arr, k) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 24,
    title: 'پیاده‌سازی map — myMap()',
    difficulty: 'medium',
    category: 'function',
    description: 'تابع map رو بدون استفاده از Array.prototype.map پیاده‌سازی کن',
    starterCode: 'function myMap(arr, fn) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 25,
    title: 'پیاده‌سازی filter — myFilter()',
    difficulty: 'medium',
    category: 'function',
    description: 'تابع filter رو بدون استفاده از Array.prototype.filter پیاده‌سازی کن',
    starterCode: 'function myFilter(arr, fn) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 26,
    title: 'پیاده‌سازی reduce — myReduce()',
    difficulty: 'hard',
    category: 'function',
    description: 'تابع reduce رو بدون استفاده از Array.prototype.reduce پیاده‌سازی کن',
    starterCode: 'function myReduce(arr, fn, initial) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 27,
    title: 'فاکتوریل — factorial()',
    difficulty: 'easy',
    category: 'logic',
    description: 'فاکتوریل یه عدد رو حساب کن',
    starterCode: 'function factorial(n) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 28,
    title: 'حذف فضاهای اضافی — removeExtraSpaces()',
    difficulty: 'easy',
    category: 'string',
    description: 'فضاهای اضافی بین کلمات رو حذف کن',
    starterCode: 'function removeExtraSpaces(str) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 29,
    title: 'camelCase به snake_case — camelToSnake()',
    difficulty: 'medium',
    category: 'string',
    description: 'یه رشته camelCase رو به snake_case تبدیل کن',
    starterCode: 'function camelToSnake(str) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 30,
    title: 'دومین بزرگترین عدد — secondLargest()',
    difficulty: 'medium',
    category: 'array',
    description: 'دومین بزرگترین عدد رو از یه آرایه پیدا کن',
    starterCode: 'function secondLargest(arr) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 31,
    title: 'شمارش کلمات — countWords()',
    difficulty: 'easy',
    category: 'string',
    description: 'تعداد کلمات یه رشته رو بشمار',
    starterCode: 'function countWords(str) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 32,
    title: 'ادغام آبجکت‌ها — mergeObjects()',
    difficulty: 'medium',
    category: 'object',
    description: 'چند آبجکت رو با هم ادغام کن (مثل Object.assign)',
    starterCode: 'function mergeObjects(...objects) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 33,
    title: 'بررسی آرایه مرتب — isSorted()',
    difficulty: 'easy',
    category: 'array',
    description: 'چک کن آیا یه آرایه به صورت صعودی مرتب شده',
    starterCode: 'function isSorted(arr) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 34,
    title: 'محدود کردن اجرا — throttle()',
    difficulty: 'hard',
    category: 'function',
    description: 'یه تابع throttle بنویس که اجرای تابع رو محدود کنه',
    starterCode: 'function throttle(fn, limit) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 35,
    title: 'پیاده‌سازی Promise.all — myPromiseAll()',
    difficulty: 'hard',
    category: 'function',
    description: 'Promise.all رو بدون استفاده از خود تابع پیاده‌سازی کن',
    starterCode: 'function myPromiseAll(promises) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 36,
    title: 'تبدیل آرایه به درخت — arrayToTree()',
    difficulty: 'hard',
    category: 'object',
    description: 'یه آرایه تخت با id و parentId رو به ساختار درختی تبدیل کن',
    starterCode: 'function arrayToTree(arr) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 37,
    title: 'بیشترین جمع زیرآرایه — maxSubarraySum()',
    difficulty: 'hard',
    category: 'array',
    description: 'زیرآرایه‌ای با بیشترین جمع ممکن پیدا کن (Kadane Algorithm)',
    starterCode: 'function maxSubarraySum(arr) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 38,
    title: 'تبدیل عدد به رومی — toRoman()',
    difficulty: 'medium',
    category: 'logic',
    description: 'یه عدد رو به اعداد رومی تبدیل کن',
    starterCode: 'function toRoman(num) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 39,
    title: 'فشرده‌سازی رشته — compressString()',
    difficulty: 'medium',
    category: 'string',
    description: 'رشته رو فشرده کن (مثلاً aabccc میشه a2bc3)',
    starterCode: 'function compressString(str) {\n  // کدت رو اینجا بنویس\n}',
  },
  {
    id: 40,
    title: 'مموایزیشن — memoize()',
    difficulty: 'hard',
    category: 'function',
    description: 'یه تابع memoize بنویس که نتایج توابع رو کش کنه',
    starterCode: 'function memoize(fn) {\n  // کدت رو اینجا بنویس\n}',
  },
];